name: My First Action

# Trigger event
on: 
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello ðŸ‘‹ GitHub Actions is working!"

      - name: Print Date
        run: date
